all: cover-letter.pdf cover-letter-resubmit.pdf

cover-letter.pdf: cover-letter.tex
	pdflatex cover-letter.tex

cover-letter-resubmit.pdf: cover-letter-resubmit.tex
	pdflatex cover-letter-resubmit.tex
