all: cover-letter.pdf cover-letter-resubmit.pdf cover-letter-resubmit-2.pdf

cover-letter.pdf: cover-letter.tex
	pdflatex cover-letter.tex

cover-letter-resubmit.pdf: cover-letter-resubmit.tex
	pdflatex cover-letter-resubmit.tex

cover-letter-resubmit-2.pdf: cover-letter-resubmit-2.tex
	pdflatex cover-letter-resubmit-2.tex
